### ISSUE TITLE
Nested Selection does not work properly

### ISSUE THREAD

**Issue by ejaz-ahmed** [vahidhedayati/ajaxdependancyselection#11]
Nested selection continent->country->  city does not work for the first field out of the box. It can be reproduced as below:

Use ads example of grails2.5 i.e testads5. Go to http://localhost:8080/testads5/myContinent/norefselectionext

And select Europe as subcontinent. Suppose I want to populate cities of France. France is selected default in select dropdown. If I click on Dropdown and hit France, no change occurs and city select dropdown still contains "Please select city". It has not populated cities of France yet probably because JQuery has not yet caught any event as France was already selected and no change took place. There is no way to populate French cities without selecting "United Kingdom" first and then select "France" again. 

Can you improve this behavior? It creates bad User experience. What should be the possible solution? Problem is caused by event generation. Since no event was generated by user action, JQuery was unable to populate next selection.

**Comment by vahidhedayati** [comment]
Hi Ejaz

This is to be expected when the gsp calls have appendName and appendValue missing.

https://github.com/vahidhedayati/testads5/commit/9ec2d02b32335686ed615361728d8b66847d6f08

by adding:
```
        appendName='Please choose'
        appendValue=''
```
To all of the g:selectPrimary secondary blocks forces the next box to default to your desired appendName and value as a default value. Leave as shown to have a blank appendValue or it could be:

 ```
        appendName='All items'
        appendValue='*'
```

Where you would then pick out star on your controller processing and make it equal to all fields in the given box.

I have updated the test project and on testads I was caught out by security which did not end up showing the streets. The Bootstrap call in testads updated to include a different way of adding the boroughs to cities:

https://github.com/vahidhedayati/testad/commit/eae66be803482b9ad42f50548f13407f8fa0f6d4#diff-680784c11e980c7d07d407d1a01abc82

**Comment by ejaz-ahmed** [comment]
Thanks @vahidhedayati for your cooperation. You are awesome.
