### ISSUE TITLE
ads:selectPrimary/Secondary Multi domainClass loading:domain3 default value how to set

### ISSUE THREAD

**Issue by Chuang-An** [vahidhedayati/ajaxdependancyselection#14]
<ads:selectPrimary id="MyDepartments141" name="MyDepartments141"
domain='ajaxdependancyselectexample.Departments'
searchField='name'
collectField='id'
noSelection="['': 'Please choose Department']" 

domain2='ajaxdependancyselectexample.Employee'
bindid="department.id"
searchField2='name'
collectField2='id'
setId="employeeID141"

domain3='ajaxdependancyselectexample.Documents'
bindid3="department.id"
searchField3='name'
collectField3='id'
setId3="documentsId141"

domain4='ajaxdependancyselectexample.Computers'
bindid4="department.id"
searchField4='pcName'
collectField4='id'
setId4="computersId141"
value=''
secondaryValue=''
?
/>

<g:select name="employee" id="employeeID141" optionKey="id" optionValue="name" from="[]" 
required="required" noSelection="['': 'Please choose department']" />
<g:select name="document" id="documentsId141" optionKey="id" optionValue="name" from="[]" 
required="required" noSelection="['': 'Please choose department']" />

**Comment by vahidhedayati** [comment]
Hi

value='1' 

secondaryValue='2'

where value is setting the value of current select box and you the define the next value for next box in the select boxing calling next.  I think primary has value and secondary value from there on you should only need to define the value if next  select box using secondary value 

https://github.com/vahidhedayati/testad/blob/master/grails-app/views/myContinent/example.gsp#L40

follow the example in link above

**Comment by Chuang-An** [comment]
I tried it,but it's not work.

**Comment by vahidhedayati** [comment]
Okay yes this hasn't been implemented as yet. Please wait until I update the plugin and provide a working example. It won't be right this second.

**Comment by vahidhedayati** [comment]
Please update the compile line of the plugin and use 1.3 of the plugin then refer to : 


https://github.com/vahidhedayati/testads/blob/master/grails-app/views/myContinent/issue14.gsp

**Comment by Chuang-An** [comment]
Thank you. It's already working.
