### ISSUE TITLE
Edit/Create Form

### ISSUE THREAD

**Issue by sergiogorniski** [vahidhedayati/ajaxdependancyselection#8]
I'm having a problem when using value and secondaryValue. When I change the selectPrimary, the "cidade" select updates, but the selectPrimary doesn't change the selected option. Am I doing something wrong?
```gsp
<g:selectPrimary 
        id="estado" name="cidade.estado.id"
	domain='com.mobiletec.erp.Estado' 
        searchField='nome' collectField='id'
	domain2='com.mobiletec.erp.Cidade' bindid="estado.id"
	searchField2='nome' collectField2='id'
	noSelection="['': 'Escolha um estado']" setId="cidade"   
        value="${configuracaoInstance?.cidade?.estado?.id}"    
       secondaryValue="${configuracaoInstance?.cidade?.id}" />

  <g:select id="cidade" name="cidade.id"
		from="[]" optionKey="id" optionValue="nome" required=""
		 noSelection="['': 'Escolha uma cidade']" class="many-to-one" />

**Comment by vahidhedayati** [comment]
Hi Sergio, I think so. I have just tested the plugin and it appears to update the primary with what was selected and then update the secondary with the relevant list.

I have just knocked up this quick demo under 2.4.4 :

https://github.com/vahidhedayati/testad/blob/master/grails-app/views/myContinent/example.gsp

and tested the primary/secondary on this example page which appeared to work fine..

Is it browser related ? try opening your browser development console and see if any js script errors / issues pop up... test in another browser?

**Comment by sergiogorniski** [comment]
Javascript error at page load: Uncaught TypeError: Cannot read property 'options' of null.
Line: var zopt = zselect.options[zselect.selectedIndex]
Tested in Firefox and IE, same problem. When I change the 'estado' select, i see it changing, but automatically changes back to the initial value.
The tag is beeing used on the _form template of scaffold.

**Comment by sergiogorniski** [comment]
Complementing the value and secondary value are working , loading normally , but after everything loaded I can't change the primary select, the setted value in GSP keeps coming back. I'm using the same page to create and edit.

**Comment by vahidhedayati** [comment]
Ok try removing set value in your primary. So no value= at all in your primary

**Comment by sergiogorniski** [comment]
Removing value works, but doesn't load the initial value, there is another way to do this?

**Comment by vahidhedayati** [comment]
Set appendName="please select " apenndValue=""

**Comment by sergiogorniski** [comment]
I dont know if you understood, my english is poor. See, my problem it's not with 'g:select id="cidade"', it's with g:selectPrimary. I can see in Javascript, that when a change selectPrimary, it calls a update method that sets again the value passed by parameter. I need to use that value to pre-load existing data, and allow users to edit. But when I try to change the selectPrimary, it calls de update function and set again the old value.

**Comment by vahidhedayati** [comment]
No sorry, some of this was my bad, your initial message was clear enough. If I had actually attempted what you were facing.
```
compile ":ajaxdependancyselection:0.42-SNAPSHOT1" 
```
Please try this and let me know how it goes.

**Comment by sergiogorniski** [comment]
Now it's working! Thank you!

**Comment by vahidhedayati** [comment]
no worries, a minor change to javascript was required. https://github.com/vahidhedayati/ajaxdependancyselection/commit/d479ecaa0f3cd047384c8663a03d97eb9ac23e31#diff-6f7b6382a5e1ca61ad24e77744bab06b. This plugin relies on too much javascript to control behaviour and can be tampered. Once boselecta goes live if websockets is an option you will find all these features exist and do no suffer these type of issues and is not so easily modifiable by end user.
