### ISSUE TITLE
Make g:autoCompletePrimary disabled

### ISSUE THREAD

**Issue by slawter** [vahidhedayati/ajaxdependancyselection#9]
Is it possible to make g:autoCompletePrimary disabled using attributes or some other ways?

**Comment by vahidhedayati** [comment]
Hi 

Sorry I am missing the point, how or what would define the starting point ? 

Can you give more info on what it is your trying to achieve and I can see how it can be changed/adopted to suite this.

**Comment by slawter** [comment]
I want to make disabled g:autoCompletePrimary input by condition, same functionality is implemented in g:select by disabled attribute (<g:select disabled=${my-condition} ... />). If condition is true, I cant input any information, that's my goal.

**Comment by vahidhedayati** [comment]
Try ajaxdependancyselection:0.42-SNAPSHOT2

Any of the autoComplete tags in this plugin should now support disabled="true"


    <g:autoCompleteSecondary
        disabled="true"

    <g:autoCompletePrimary
        disabled="true"

**Comment by slawter** [comment]
Ok. thank you, I'll try ajaxdependancyselection:0.42-SNAPSHOT2

**Comment by slawter** [comment]
It seems like option require="false" doesn't work for g:autoCompletePrimary ajaxdependancyselection:0.42-SNAPSHOT2

**Comment by vahidhedayati** [comment]
thanks, can you please try SNAPSHOT3 and see how it goes?

**Comment by slawter** [comment]
Now it works well. Thank you very much.

**Comment by vahidhedayati** [comment]
Cool I presume this now includes disabled auto complete (as in this is now working too )

**Comment by slawter** [comment]
Autocomplete is working well
